---
- name: brew update
  homebrew: update_homebrew=yes

- name: Install required software
  homebrew: name={{ item }} state=present
  with_items:
      - ack
      - brew-cask
      - ctags
      - git
      - gnupg
      - jenv
      - jq
      - leiningen
      - openssl
      - the_silver_searcher
      - tig
      - vim

- name: Install ancillary applications
  homebrew_cask: name={{ item }} state=present
  with_items:
      - appcleaner
      - caffeine
      - clamxav
      - dropbox
      - evernote
      - firefox
      - google-chrome
      - iterm2
      - keepassx
      - opera
      - pgadmin3
      - private-eye
      - robomongo
      - skype
      - sourcetree
      - spectacle
      - spideroak
      - tunnelblick
      - vagrant
      - virtualbox
      - vlc
