---
- name: Install required software
  homebrew: name={{ item }} state=present
  with_items:
      - ack
      - git
      - vim

- name: Install ancillary applications
  homebrew_cask: name={{ item }} state=present
  with_items:
      - firefox
      - google-chrome
      - virtualbox
      - vagrant
