---
- homebrew:
    name: gnupg,jq,tig,vim
    state: latest
    update_homebrew: yes

- homebrew_cask:
    name: caffeine,firefox,google-chrome,intellij-idea,skype,vagrant,virtualbox
    state: present

- name: iterm2 is a diva when it comes to installing
  block:
    - homebrew_cask:
        name: iterm2
        state: present
  rescue:
    - debug:
        msg: 'ignore failure message above, iterm2 is already installed'

- homebrew_cask:
    upgrade_all: true

